### ISSUE TITLE
Inkscape doesn't want to open

### ISSUE THREAD

**Issue by ramuntcho** [valerioa/Inkscape-MacOS-Curated-Build#1]
Hi,

This project is great, thanks !!!
Inkscape doesn't want to open ; i have tested on macOS 10.9.5, 10.12.6, 10.13.1. I have always this window which appears (in french). I have also joined the log files.
<img width="419" alt="window" src="https://user-images.githubusercontent.com/2462665/33598871-9b2300c0-d9a4-11e7-9ac3-5b4ba68063cd.png">

[LogInkscape_macOS10.9.5.txt](https://github.com/valerioa/Inkscape-MacOS-Curated-Build/files/1530431/LogInkscape_macOS10.9.5.txt)

[LogInkscape_macOS10.12.6.txt](https://github.com/valerioa/Inkscape-MacOS-Curated-Build/files/1530435/LogInkscape_macOS10.12.6.txt)

[Log_Inkscape_macOS10.13.1.txt](https://github.com/valerioa/Inkscape-MacOS-Curated-Build/files/1530418/Log_Inkscape_macOS10.13.1.txt)

**Comment by valerioa** [comment]
Hello,

the problem is caused by the fact that you installed Inkscape as '/Applications/InkscapeNatif.app'

Currently the application path is hard-coded. Inkscape needs to be installed as '/Applications/Inkscape.app'

If you can do that It will run.

**Comment by ramuntcho** [comment]
Hi, 

In fact, there was 2 problems. In 2 macs, i rename Inkscape.app as InkscapeNatif.app, and in the third one, the application Inkscape.app was on the Desktop. Everything's fine now.

:-))  Christian
