### ISSUE TITLE
Menu: Path - Trace Pixel arts... freeze Inkscape

### ISSUE THREAD

**Issue by linediconsine** [valerioa/Inkscape-MacOS-Curated-Build#10]
HI All,

One of the cool feature of Inkscape is auto trace ( convert PNG to SVG)
![screen shot 2018-01-23 at 1 07 39 pm](https://user-images.githubusercontent.com/1525362/35293259-2ee3e690-0041-11e8-8edb-7bb7f80a141c.png)

Steps: 
v.0.92
1.Import JPG
2.select JPG 
3. PATH - Trace Pixel arts

Inkscape freeze (NOTE: drawing is freezing, menu is still working)

**Comment by valerioa** [comment]
I think "Trace Pixel Art" actually does work. It works in 0.92.3v2 and it likely worked in 0.92.2 too.
For the image you're trying to trace, you should have used "Trace Bitmap".
"Trace Pixel Art" is for pixelated images, but the algorithm is likely O(m . n), or, worse, O((m . n)^x). Thus it will take a very long time to trace the image you have. But, if you try it on a truly pixelated tiny image like the one below:

![image](https://user-images.githubusercontent.com/737428/50502655-1cccef00-0a1e-11e9-9115-794884e43077.png)

It does work.

"Trace Bitmap" works great as well. Please try https://github.com/valerioa/Inkscape-MacOS-Curated-Build/releases/tag/0.92.3.quartz.v2
