### ISSUE TITLE
error on open, os x sierra

### ISSUE THREAD

**Issue by rteest53** [valerioa/Inkscape-MacOS-Curated-Build#13]
received error message: version not compatible with current os version. was looking forward to uninstalling current version of inkscape requiring quartz.

thought about uninstalling current version of inkscape and quartz and giving another go on version 6, but thought that would be futile considering the incompatibility with os x sierra error message.

**Comment by valerioa** [comment]
I compile it on Sierra, and, I run it on Sierra every day. Never seen any problem. Nobody else has ever complained. Most users run it on Sierra. I suspect there is a different issue.

**Comment by rteest53** [comment]
i think my problem was that i still had quartz installed. i 'completely'
removed quartz (except that needed for the system) after uninstalling
inkscape v6. i reinstalled and had a bit of a glitch with the preferences
resetting to default after saving the changes to the default template.
can't remember what i did, if anything, but the prefs have been holding.

another glitch reared its head. i also had added the layers, transform,
text and fonts and fill and stroke palettes and they did not appear when
the program opened. it seems that the palettes were very slow to open, but
have since showed themselves all but immediately upon starting the program.

this version of inkscape opens much quicker that the web site version did;
and since there is no 9.2.3 version for mac, is now my preferred version of
the program. i think it would behoove the developers to consider assisting
this developer, especially for the mac, in bringing the current 9.2.3
version to their code base. this has been something that the developers of
inkscape have been requesting for some time now, to have a version of
inkscape without having to install quartz to make it work.

please, please, please help valerio. this developer has been developing
this since december of last year and has made this kind of progress in
under a year. it is written, ask and you shall receive, well, you asked and
now have received. mac users of inkscape now have a version that starts
quicker and uses mac keyboard commands (i.e. cmd+q not ctrl+q to close the
program) to operate the program. your, our, wish has been granted. your,
our, request has been granted. your, our, prayer has been answered.

i'm an end user, not a programmer. what can i do to help move this
developer into the main stream of inkscape development. i'm a quick study.
i could learn to compile with xcode with some instruction if anyone would
care to teach me. if i can write html and css, how different is it to
complie with the proper instruction?

**Comment by valerioa** [comment]
Please try https://github.com/valerioa/Inkscape-MacOS-Curated-Build/releases/tag/0.92.3.quartz.v2
It should solve most if not all the problems you had. If not, please reopen an issue
