### ISSUE TITLE
No Icon in Bundle & weird messages on exit

### ISSUE THREAD

**Issue by paaguti** [valerioa/Inkscape-MacOS-Curated-Build#17]
Hi, 

this is a significant improvement :-) Congrats. Things I see now are:

* Icon missing in bundle

And the attached messages on exit
![inkscape-0923](https://user-images.githubusercontent.com/3320432/50479179-896fcb80-09d5-11e9-9e9f-8caa37b1e8c6.png)

Keep up with the good work!

Happy New Year

**Comment by valerioa** [comment]
Compare to the rest, those were easy fixes. Fixed in  https://github.com/valerioa/Inkscape-MacOS-Curated-Build/releases/tag/0.92.3.quartz.v2
