### ISSUE TITLE
Inkscape for MacOS 64 Bit Install vs 32 Bit Install

### ISSUE THREAD

**Issue by jimbox13** [valerioa/Inkscape-MacOS-Curated-Build#19]
![inkscape-mac-32bit_922](https://user-images.githubusercontent.com/7525774/50613533-0a7a0780-0e9b-11e9-93b1-c7b74780457d.png)

It appears that my Inkscape is 32 bit - unless I'm reading this wrong.  Does that mean I've installed a version that is different than the one in this repo?

**Comment by valerioa** [comment]
That looks like a different version from the one I compile. Mine is guaranteed 64bit:
<pre>
>> file /Applications/Inkscape.app/Contents/Resources/bin/inkscape
/Applications/Inkscape.app/Contents/Resources/bin/inkscape: Mach-O 64-bit executable x86_64
</pre>

Also the executable I compile is called "Inkscape" and not inkscape-bin (see the row below the one highlighted in your picture). Mine starts with a bash script that exec() the binary inkscape, so there should only be one process called "Inkscape"

![image](https://user-images.githubusercontent.com/737428/50614274-7cebe700-0e9d-11e9-96a8-c9191803a35e.png)


I suggest you move to Trash all folders named "Inkscape" in your /Applications folder and download the latest one: 
https://github.com/valerioa/Inkscape-MacOS-Curated-Build/releases/tag/0.92.3.quartz.v1
and copy the app into the /Applications folder.

**Comment by jimbox13** [comment]
Interesting!  I installed .92 perhaps a year or so ago from the official Inkscape site under the Mac download section.  I know their site says they don't have any newer version but I'm pretty sure I downloaded this:   `https://inkscape.org/release/inkscape-0.92.2/mac-os-x/107/dmg/dl/`
file named:  `Inkscape-0.92.2-1-x11-10.7-x86_64.dmg`

Is that the same as yours? I use inkscape every day and part of that work is to create Plain SVGs for my cutting machine.  Will that compatibility change with your version?  Just curious to what the difference is.

**Comment by valerioa** [comment]
I see. This is a separate/distinct compile from the mainstream Inkscape. My compile has a tighter integration with the Mac OSX operating system, including, but not limited to, better clipboard/pasteboard sync - copy and paste pdf and other vector formats, OSX look and feel and menus, OSX shortcut keys and many others. The codebase is the same, so whatever you do with SVG files with the mainstream, you should be able to do with this compile. Do let me know if you spot differences.
