### ISSUE TITLE
The tool "Remplissage au seau" isn't present in the tool menu

### ISSUE THREAD

**Issue by ramuntcho** [valerioa/Inkscape-MacOS-Curated-Build#2]
Hi,
It seems that a tool isn't present in tool menu (and in the preferences, we don't find it)

Your build
<img width="54" alt="capture d ecran 2017-12-05 16 31 52" src="https://user-images.githubusercontent.com/2462665/33615250-f759f760-d9d9-11e7-9a36-61c582928c5a.png">

The build with Quartz
<img width="59" alt="capture d ecran 2017-12-05 16 31 41" src="https://user-images.githubusercontent.com/2462665/33615261-fe834ca8-d9d9-11e7-89f9-f9586a208743.png">

**Comment by valerioa** [comment]
That's interesting. I wil look into it

**Comment by Moini** [comment]
Sounds like potrace is missing while building. It's needed for trace bitmap and for the bucket tool.

**Comment by valerioa** [comment]
This is has been fixed in the latest release
https://github.com/valerioa/Inkscape-MacOS-Curated-Build/releases/tag/0.92.3.quartz.v1

**Comment by Moini** [comment]
@valerioa Hi :) Thank you! 

I was wondering if you would like to join the efforts for creating a Mac version for Inkscape 1.0 (which uses Gtk3, and thus will require some work) - maybe not doing the actual work, if you don't have time for it, but giving expert advice to those who do?

I'm inviting you to pop over to https://chat.inkscape.org/channel/mac-dev :)
