### ISSUE TITLE
User font directory omitted

### ISSUE THREAD

**Issue by Rastafabisch** [valerioa/Inkscape-MacOS-Curated-Build#21]
This is actually an [old issue](https://github.com/valerioa/Inkscape-MacOS-Curated-Build/issues/15#issuecomment-452635238).

The user's font directory is not taken into account. `~/Library/Fonts/`

Apart from this I highly appreciate your builds. A great service tor the Mac and OpenSource community. Well done.

**Comment by sven-strothoff** [comment]
This seems to be fixed already in commit 3c0015cb775dcc080d99fc853a5a07ac08570be4.

**Comment by sven-strothoff** [comment]
I just applied the changes manually to my installed Inkscape and the user fonts are working now. If you don't want to wait for a new build, just edit the files in `/Applications/Inkscape.app/Contents/Resources/etc/fonts/conf.d`.
Thanks for the quick fix!

**Comment by Rastafabisch** [comment]
Great. So this issue can be regarded as fixed.

**Comment by Lazza** [comment]
_Note to self_ (because I missed it at first): the file `userfonts.conf` **must be renamed** to `10-userfonts.conf`, you cannot just fix its contents by correcting the XML.
