### ISSUE TITLE
Resizing is difficult

### ISSUE THREAD

**Issue by ramuntcho** [valerioa/Inkscape-MacOS-Curated-Build#3]
Hi,

2 problems :
- the small zone which allows to resize easily is absent, so it's difficult to resize ; mainly we make a zoom (your build first)

- resizing makes the screen crazy, see screencast (zip file)

<img width="98" alt="capture d ecran 2017-12-05 16 38 14" src="https://user-images.githubusercontent.com/2462665/33615575-c81d3556-d9da-11e7-9330-e0319fdf95fa.png">
<img width="132" alt="capture d ecran 2017-12-05 16 38 29" src="https://user-images.githubusercontent.com/2462665/33615933-b39244e0-d9db-11e7-9bfe-fa5281cea1f7.png">

[ScreenFlow_0.mp4.zip](https://github.com/valerioa/Inkscape-MacOS-Curated-Build/files/1531782/ScreenFlow_0.mp4.zip)

**Comment by valerioa** [comment]
Resizing trouble is due to the GTK widget style (Zukitwo). I'll try and force the same widget style that GIMP use. Messy screen during resizing is likely due to Inkscape/Gtk/Quartz interoperation, nothing I can do there

**Comment by valerioa** [comment]
Resizing fixed in 0.92.2.quartz.v2. - Messy work-area refresh likely needs a fix in gtk2

**Comment by ramuntcho** [comment]
Hello,

Nothing changes with this release, sorry. The arrows for zooming are in the corner, there isn't a small zone to "grip" the windows to resize it.

**Comment by valerioa** [comment]
It's the theme engine and style. Try putting the pointer just outside the corner, click and resize from there
![image](https://user-images.githubusercontent.com/737428/33801447-98c4e3b2-dd18-11e7-907e-1bfa1377c41b.png)

It works for me.

**Comment by ramuntcho** [comment]
Hello Valerio,

We are thinking to replace in our school computers Inkscape classical by your version for next year. But i have one question, both versions take a long long for the first launch. Is it a way to avoid this ? is there some cache files that we can use ?

Thanks in advance for your answer

:-)) Christian

________________________________
Christian Oïhénart
SEM-Logistique
Etat de Genève - Service Ecoles-Médias
Rue des Gazomètres 3 - CP 241 - 1211 Genève 8
Tél. 022 388 63 76
christian.oihenart@edu.ge.ch<mailto:christian.oihenart@edu.ge.ch>

**Comment by ramuntcho** [comment]
Hi Valerio,

Any idea ?

:-)) Christian

________________________________
Christian Oïhénart
SEM-Logistique
Etat de Genève - Service Ecoles-Médias
Rue des Gazomètres 3 - CP 241 - 1211 Genève 8
Tél. 022 388 63 76
christian.oihenart@edu.ge.ch<mailto:christian.oihenart@edu.ge.ch>





Le 14 janv. 2018 à 17:46, Oihenart Christian (EDU) <christian.oihenart@edu.ge.ch<mailto:christian.oihenart@edu.ge.ch>> a écrit :


Hello Valerio,

We are thinking to replace in our school computers Inkscape classical by your version for next year. But i have one question, both versions take a long long for the first launch. Is it a way to avoid this ? is there some cache files that we can use ?

Thanks in advance for your answer

:-)) Christian

________________________________
Christian Oïhénart
SEM-Logistique
Etat de Genève - Service Ecoles-Médias
Rue des Gazomètres 3 - CP 241 - 1211 Genève 8
Tél. 022 388 63 76
christian.oihenart@edu.ge.ch<mailto:christian.oihenart@edu.ge.ch>

**Comment by valerioa** [comment]
Inkscape uses fonts through the freetype2 and fontconfig libraries. At the first start, it rebuilds the fontconfig cache, in order to be able to use all fonts installed on your Mac. after the first start, next starts should be much faster. It cannot be avoided: you would not be able to use all of your fonts, if it did not do that.
