### ISSUE TITLE
Pasting doesn't work (Command-V also)

### ISSUE THREAD

**Issue by ramuntcho** [valerioa/Inkscape-MacOS-Curated-Build#4]
Hi,

Command-c and command-x are ok, but impossible to paste the object. In fact, pasting isn't possible, even wih the menu.

**Comment by valerioa** [comment]
Copying & Pasting works great for me from Preview. What are you trying to copy and paste. OPen a PDF in Preview, copy it and paste it in Inkscape. Works for me

**Comment by valerioa** [comment]
I see what you mean, copying and pasting from inside Inkscape. I'll look into that. To copy an object in Inkscape I sue Cmd+D

**Comment by valerioa** [comment]
Thank you for finding this. It's fixed in 0.92.2.quartz.v2

**Comment by ramuntcho** [comment]
Great, it's working fine
