### ISSUE TITLE
Font issue with Thai "sara am" อำ alignment

### ISSUE THREAD

**Issue by jeffmcneill** [valerioa/Inkscape-MacOS-Curated-Build#6]
In the latest build the Thai character "sara am" อำ is misaligned. As viewed to the left, the small circle is placed above and to the right of the "au ang" อ. On a Thai keyboard, the au ang is lowercase v and the sara am is lowercase e. Sara am is a vowel which needs a consonant (or default au ang consonant. Support for South Asian scripts allows for this behavior (of the vowel to the left, right, above, and/or below a consonant. Inkscape has no problem with Thai fonts and South Asian scripts in general. For some reason the latest version of Inkscape breaks the intended (and previously support) use of the sara am character. For example: ทำนา which means "to work a rice field (farming)", the small circle is above the sara ah character (the candy cane-looking character). This applies across the board to all fonts.

Below, in the image, the first placement is incorrect, with the new Inkscape. The second placement is correct, with the older version of Inkscape.

![screen shot 2017-12-17 at 15 44 42](https://user-images.githubusercontent.com/3119827/34077970-f058e8b4-e342-11e7-8073-cfcfa21b8f7b.png)

**Comment by valerioa** [comment]
Jeff- thanks so much for such a thorough testing. I am inclined to think that is a problem with Inkscape proper, or with the freetype2/harfbuzz libraries (libraries that render fonts). Nothing I can fix with the MacOS integration.

**Comment by jeffmcneill** [comment]
The alignment of the tone marks (อ่ อ้ อ๊ อ๋) are actually improved in the new Inkscape, in some fonts, but the misalignment of the sara am is a showstopper for me. Do you know of a place I can submit a bug report regarding this issue for the libraries? I've never seen only a single character with an issue, normally everything is supported or everything is not supported (regarding South Asian scripts). Note: Thai is not South Asian, but it comes from that lineage, and generally has the same issues as other Brahmi-derrived scripts. Same issues can occur in Myanmar/Burmese, Lao, and Khmer.

**Comment by valerioa** [comment]
Does the same problem manifest with the Inkscape MacOS version downloaded from https://inkscape.org/en/release/0.92.2/ ? If so you should submit a bug to https://bugs.launchpad.net/inkscape . It could be a problem with freetype2, it might be interesting to test the same font with another app that uses freetype2 (ex. GIMP).

**Comment by jeffmcneill** [comment]
Yes, same problem in the 0.92.2 release. I'll follow up as you suggest. Thank you for your time on this issue. I really like the new release, but will have to wait for this bug to get fixed upstream.

**Comment by jeffmcneill** [comment]
Known bug since 2.5+ years ago, they have a work around but are not implementing it. Sad. https://bugs.launchpad.net/inkscape/+bug/1425387

**Comment by jeffmcneill** [comment]
Note: the code that needs to be commented out (that creates this problem) starts on line 1281 here: https://github.com/valerioa/Inkscape-MacOS-Curated-Build/blob/master/src/libnrtype/Layout-TNG-Compute.cpp

Not sure where it ends, but commenting out might due the trick.

**Comment by valerioa** [comment]
Where is the patch? Maybe from time to time I can make a Thai only release.

**Comment by jeffmcneill** [comment]
See merge request

**Comment by valerioa** [comment]
Since the release of Inkscape 1.0, and following versions, this project has no reason to exist anymore. Inkscape 1.0 (Inkscape 1.1.1 at the time of this writing - https://inkscape.org/gallery/item/29282/Inkscape-1.1.1.dmg ) is fully integrated with the Mac OSX UI. The 1.x.x Inkscape has Mac-style menus and window decorations. Granted, it is not perfect: the clipboard integration still has some problems (November 2021). However, Inkscape 1.x.x takes advantage of all the bugfixes and improvement that have been developed. I advise all to install the most recent version of Inkscape 1.x.x.
