### ISSUE TITLE
character "h" and "v" toggles object flip

### ISSUE THREAD

**Issue by ghost** [valerioa/Inkscape-MacOS-Curated-Build#7]
running Inkscape on Mac 10.13.2 I have a bug in which the letter "h" cannot be typed, rather it seems mapped to Object-> Flip Horizontal command. Likewise, "v" toggles the Flip Vertical command.

**Comment by valerioa** [comment]
Hi, thank you for noticing the problem. It is fixed in release v4 - https://github.com/valerioa/Inkscape-MacOS-Curated-Build/releases/tag/0.92.2.quartz.v4

I'm closing this issue.
