### ISSUE TITLE
Weird behavior while I am scaling the Inkscape window

### ISSUE THREAD

**Issue by linediconsine** [valerioa/Inkscape-MacOS-Curated-Build#9]
HI Valerio,

I see a weird images while I am scaling the inkscepe window,
Version 0.92

Example:
![screen shot 2018-01-23 at 9 31 38 am](https://user-images.githubusercontent.com/1525362/35281156-3ba19c9a-0020-11e8-8a22-59bebf1fc7a2.png)

Thanks 

MArco

**Comment by valerioa** [comment]
This is due likely to scaling byte or word boundaries used by Inkscape and quartz/gtk that are not matching. This has to be fixed upstream, nothing I can fix here.
